services:
  alquiler-db:
    image: postgres:16
    container_name: alquiler-db
    restart: always
    environment:
      TZ: America/Lima
      POSTGRES_DB: sistema_alquiler
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - alquiler_db_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - alquiler-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  alquiler-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: alquiler-app
    restart: unless-stopped
    depends_on:
      alquiler-db:
        condition: service_healthy
    environment:
      TZ: America/Lima
      JAVA_TOOL_OPTIONS: -Duser.timezone=America/Lima
      SPRING_DATASOURCE_URL: jdbc:postgresql://alquiler-db:5432/sistema_alquiler
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - alquiler-net


volumes:
  alquiler_db_data:

networks:
  alquiler-net:
